"""Data-contract schemas for SentinelAI's security event pipeline.

Convenience re-exports for the canonical schemas consumed across the
pipeline (raw security event, normalized event, enriched event, the
Threat Intelligence Agent contract, the Detection subsystem contracts,
the Step 10A Correlation domain contract, the Step 11A Risk Assessment
domain contract, the Step 12A Investigation domain contract, the
Step 12B Investigation Context builder contract, the Step 13
Investigation Knowledge & RAG Layer contracts, the Step 14 Threat
Attribution domain contract, the Step 24 Policy Decision domain contract,
and the Step 25 Response & Mitigation domain contract).
Consumers may import from this package or from the individual modules;
both paths are equivalent.
"""

from app.schemas.detection import (
    DetectionEvidence,
    DetectionMetadata,
    DetectionResult,
    DetectionRule,
    DetectionSeverity,
    RuleType,
)
from app.schemas.detection_agent import (
    DetectionAnalysis,
    DetectionAnalysisMetadata,
    DetectionFailure,
)
from app.schemas.detection_query import (
    DetectionAnalysisRecord,
    DetectionAnalysisSummary,
    DetectionFailurePage,
    DetectionFailureRecord,
    DetectionResultPage,
    DetectionResultRecord,
)
from app.schemas.correlation_query import (
    CorrelationMemberRecord,
    CorrelationPage,
    CorrelationResultRecord,
)
from app.schemas.correlation import (
    CorrelationMember,
    CorrelationResult,
    CorrelationStatus,
    to_correlation_members,
)
from app.schemas.detection_correlation import (
    DetectionCorrelationBatch,
    DetectionCorrelationBatchMetadata,
    DetectionCorrelationInput,
    to_correlation_batch,
    to_correlation_input,
)
from app.schemas.enriched_event import (
    EnrichedSecurityEvent,
    EnrichmentResult,
)
from app.schemas.normalized_event import (
    Actor,
    Endpoint,
    EventCategory,
    EventOutcome,
    FileInfo,
    NormalizedSecurityEvent,
    ProcessInfo,
)
from app.schemas.security_event import (
    Provenance,
    SecurityEvent,
    SourceType,
)
from app.schemas.threat_intelligence_agent import (
    ExtractedIndicator,
    ProviderAssociation,
    ProviderFailure,
    ThreatIntelMetadata,
    ThreatIntelligenceAnalysis,
    THREAT_INTELLIGENCE_ENRICHMENT_TYPE,
    threat_intel_result_to_enrichment,
)
from app.schemas.risk_query import (
    RiskAssessmentPage,
    RiskAssessmentRecord,
)
from app.schemas.risk import (
    RiskAssessment,
    RiskEvidence,
    RiskFactor,
    RiskLevel,
)
from app.schemas.investigation import (
    InvestigationEvidence,
    InvestigationFinding,
    InvestigationObservation,
    InvestigationResult,
)
from app.schemas.investigation_context import (
    ContextInputAvailability,
    CorrelationContext,
    CorrelationMemberContext,
    DetectionContext,
    EnrichmentContext,
    EventProvenanceContext,
    IncidentMemoryReferenceContext,
    IndicatorContext,
    InputAvailability,
    InvestigationContext,
    InvestigationContextBuilder,
    InvestigationContextBoundError,
    InvestigationContextError,
    MAX_INCIDENT_MEMORY_REFERENCES,
    ProviderFailureContext,
    ProviderLookupContext,
    ProviderResultContext,
    RiskContext,
    ThreatIntelligenceContext,
)
from app.schemas.knowledge import (
    KnowledgeBoundError,
    KnowledgeChunk,
    KnowledgeDocument,
    KnowledgeIndexRecord,
    KnowledgeItem,
    KnowledgeType,
    KnowledgeValidationError,
)
from app.schemas.knowledge_context import (
    InvestigationKnowledgeContext,
    KnowledgeRetrievalMetadata,
    build_investigation_knowledge_context,
)
from app.schemas.threat_attribution import (
    AttributionAssessment,
    AttributionEvidence,
    AttributionHypothesis,
    AttributionStatus,
    AttributionTargetType,
    MAX_ATTRIBUTION_EVIDENCE_ITEMS,
    MAX_ATTRIBUTION_HYPOTHESES,
    MAX_ATTRIBUTION_LABEL_LENGTH,
    MAX_ATTRIBUTION_METADATA_DEPTH,
    MAX_ATTRIBUTION_METADATA_SERIALIZED_BYTES,
    MAX_ATTRIBUTION_TARGET_IDENTIFIER_LENGTH,
)
from app.schemas.incident_memory import (
    MAX_MEMORY_ACTIONS,
    MAX_MEMORY_ENTITIES,
    MAX_MEMORY_FINDINGS,
    MAX_MEMORY_IDENTIFIER_LENGTH,
    MAX_MEMORY_INDICATORS,
    MAX_MEMORY_LABEL_LENGTH,
    MAX_MEMORY_METADATA_DEPTH,
    MAX_MEMORY_METADATA_SERIALIZED_BYTES,
    MAX_MEMORY_SOURCE_REFERENCES_PER_ITEM,
    MAX_MEMORY_SOURCES,
    MAX_MEMORY_SUMMARY_LENGTH,
    MAX_MEMORY_TECHNIQUES,
    MAX_MEMORY_TECHNIQUE_CODE_LENGTH,
    MAX_MEMORY_TITLE_LENGTH,
    MAX_MEMORY_VALUE_LENGTH,
    IncidentMemory,
    MemoryAction,
    MemoryEntity,
    MemoryFinding,
    MemoryIndicator,
    MemoryOutcome,
    MemorySource,
    MemoryTechnique,
    MemoryType,
)

from app.schemas.incident_memory_learning import (
    IncidentMemoryLearning,
    IncidentMemoryLearningResult,
    LearningOutcomeInfo,
    LearningType,
    MAX_LEARNING_METADATA_DEPTH,
    MAX_LEARNING_METADATA_SERIALIZED_BYTES,
    MAX_LEARNING_OUTPUT_RECORDS,
    MAX_LEARNING_PATTERN_KEY_LENGTH,
    MAX_LEARNING_PATTERN_VALUE_LENGTH,
    MAX_LEARNING_SUPPORTING_MEMORY_REFERENCES,
)

from app.schemas.soc_query import (
    SOC_DEFAULT_PAGE_SIZE,
    SOC_DEFAULT_RECENT_LIMIT,
    SOCExecutionMetadata,
    SOCExecutionMode,
    SOCFilters,
    SOC_INTENT_MODEL_JSON_SCHEMA,
    SOC_MAX_MODEL_OUTPUT_BYTES,
    SOC_MAX_PAGE_SIZE,
    SOC_MAX_QUERY_LENGTH,
    SOC_MAX_RECENT_LIMIT,
    SOC_MAX_RULE_ID_LENGTH,
    SOCModelIntent,
    SOCOperation,
    SOCPagination,
    SOCQueryIntent,
    SOCQueryRequest,
    SOCQueryResponse,
    SOCQueryTarget,
    SOCResource,
)

from app.schemas.policy_decision import (
    POLICY_DECISION_NAMESPACE,
    POLICY_MAX_EVIDENCE_REFERENCES,
    POLICY_MAX_ROLE_LENGTH,
    POLICY_MAX_RULE_ID_LENGTH,
    PolicyDecision,
    PolicyDecisionStatus,
    PolicyEvidence,
    PolicyEvidenceType,
    PolicyInput,
    PolicyRule,
    ResponseActionType,
    risk_rank,
)

from app.schemas.response import (
    RESPONSE_ID_NAMESPACE,
    RESPONSE_IDEMPOTENCY_NAMESPACE,
    RESPONSE_MAX_ERROR_CODE_LENGTH,
    RESPONSE_MAX_MESSAGE_LENGTH,
    RESPONSE_MAX_METADATA_DEPTH,
    RESPONSE_MAX_PROVIDER_LENGTH,
    RESPONSE_MAX_TARGET_LENGTH,
    ResponseExecutionStatus,
    ResponseRequest,
    ResponseResult,
)

from app.schemas.approval import (
    APPROVAL_DECISION_STATUSES,
    APPROVAL_MAX_COMMENT_LENGTH,
    APPROVAL_MAX_REASON_LENGTH,
    APPROVAL_MAX_ROLE_LENGTH,
    APPROVAL_MAX_RULE_ID_LENGTH,
    APPROVAL_MAX_TARGET_LENGTH,
    APPROVAL_NAMESPACE,
    APPROVAL_PENDING_TTL,
    APPROVAL_TERMINAL_STATUSES,
    ApprovalDecisionInput,
    ApprovalPage,
    ApprovalRecord,
    ApprovalRequestCreate,
    ApprovalStatus,
)

__all__ = [
    "SecurityEvent",
    "SourceType",
    "Provenance",
    "NormalizedSecurityEvent",
    "EventCategory",
    "EventOutcome",
    "Actor",
    "Endpoint",
    "ProcessInfo",
    "FileInfo",
    "EnrichmentResult",
    "EnrichedSecurityEvent",
    "ExtractedIndicator",
    "ProviderAssociation",
    "ProviderFailure",
    "ThreatIntelMetadata",
    "ThreatIntelligenceAnalysis",
    "THREAT_INTELLIGENCE_ENRICHMENT_TYPE",
    "threat_intel_result_to_enrichment",
    "RuleType",
    "DetectionSeverity",
    "DetectionEvidence",
    "DetectionMetadata",
    "DetectionRule",
    "DetectionResult",
    "DetectionAnalysis",
    "DetectionAnalysisMetadata",
    "DetectionFailure",
    "DetectionResultRecord",
    "DetectionFailureRecord",
    "DetectionAnalysisSummary",
    "DetectionAnalysisRecord",
    "DetectionResultPage",
    "DetectionFailurePage",
    "CorrelationMemberRecord",
    "CorrelationResultRecord",
    "CorrelationPage",
    "DetectionCorrelationInput",
    "DetectionCorrelationBatch",
    "DetectionCorrelationBatchMetadata",
    "to_correlation_input",
    "to_correlation_batch",
    "CorrelationStatus",
    "CorrelationMember",
    "CorrelationResult",
    "to_correlation_members",
    "RiskLevel",
    "RiskEvidence",
    "RiskFactor",
    "RiskAssessment",
    "RiskAssessmentRecord",
    "RiskAssessmentPage",
    "InvestigationEvidence",
    "InvestigationFinding",
    "InvestigationObservation",
    "InvestigationResult",
    "InputAvailability",
    "ContextInputAvailability",
    "CorrelationMemberContext",
    "CorrelationContext",
    "RiskContext",
    "DetectionContext",
    "IndicatorContext",
    "ProviderResultContext",
    "ProviderLookupContext",
    "ProviderFailureContext",
    "ThreatIntelligenceContext",
    "EnrichmentContext",
    "EventProvenanceContext",
    "InvestigationContext",
    "InvestigationContextError",
    "InvestigationContextBoundError",
    "InvestigationContextBuilder",
    "KnowledgeType",
    "KnowledgeDocument",
    "KnowledgeChunk",
    "KnowledgeItem",
    "KnowledgeIndexRecord",
    "KnowledgeValidationError",
    "KnowledgeBoundError",
    "KnowledgeRetrievalMetadata",
    "InvestigationKnowledgeContext",
    "build_investigation_knowledge_context",
    "AttributionStatus",
    "AttributionTargetType",
    "AttributionEvidence",
    "AttributionHypothesis",
    "AttributionAssessment",
    "MAX_ATTRIBUTION_HYPOTHESES",
    "MAX_ATTRIBUTION_EVIDENCE_ITEMS",
    "MAX_ATTRIBUTION_TARGET_IDENTIFIER_LENGTH",
    "MAX_ATTRIBUTION_LABEL_LENGTH",
    "MAX_ATTRIBUTION_METADATA_DEPTH",
    "MAX_ATTRIBUTION_METADATA_SERIALIZED_BYTES",
    "MemoryType",
    "MemorySource",
    "MemoryIndicator",
    "MemoryEntity",
    "MemoryTechnique",
    "MemoryFinding",
    "MemoryAction",
    "MemoryOutcome",
    "IncidentMemory",
    "MAX_MEMORY_TITLE_LENGTH",
    "MAX_MEMORY_SUMMARY_LENGTH",
    "MAX_MEMORY_LABEL_LENGTH",
    "MAX_MEMORY_IDENTIFIER_LENGTH",
    "MAX_MEMORY_VALUE_LENGTH",
    "MAX_MEMORY_TECHNIQUE_CODE_LENGTH",
    "MAX_MEMORY_SOURCES",
    "MAX_MEMORY_INDICATORS",
    "MAX_MEMORY_ENTITIES",
    "MAX_MEMORY_TECHNIQUES",
    "MAX_MEMORY_FINDINGS",
    "MAX_MEMORY_ACTIONS",
    "MAX_MEMORY_METADATA_DEPTH",
    "MAX_MEMORY_METADATA_SERIALIZED_BYTES",
    "MAX_MEMORY_SOURCE_REFERENCES_PER_ITEM",
    "LearningType",
    "LearningOutcomeInfo",
    "IncidentMemoryLearning",
    "IncidentMemoryLearningResult",
    "MAX_LEARNING_PATTERN_KEY_LENGTH",
    "MAX_LEARNING_PATTERN_VALUE_LENGTH",
    "MAX_LEARNING_METADATA_DEPTH",
    "MAX_LEARNING_METADATA_SERIALIZED_BYTES",
    "MAX_LEARNING_SUPPORTING_MEMORY_REFERENCES",
    "MAX_LEARNING_OUTPUT_RECORDS",
    "SOCResource",
    "SOCOperation",
    "SOCExecutionMode",
    "SOCModelIntent",
    "SOCFilters",
    "SOCQueryTarget",
    "SOCPagination",
    "SOCQueryIntent",
    "SOCExecutionMetadata",
    "SOCQueryResponse",
    "SOCQueryRequest",
    "SOC_INTENT_MODEL_JSON_SCHEMA",
    "SOC_MAX_QUERY_LENGTH",
    "SOC_MAX_MODEL_OUTPUT_BYTES",
    "SOC_MAX_PAGE_SIZE",
    "SOC_MAX_RECENT_LIMIT",
    "SOC_DEFAULT_PAGE_SIZE",
    "SOC_DEFAULT_RECENT_LIMIT",
    "SOC_MAX_RULE_ID_LENGTH",
    "PolicyDecision",
    "PolicyDecisionStatus",
    "PolicyEvidence",
    "PolicyEvidenceType",
    "PolicyInput",
    "PolicyRule",
    "ResponseActionType",
    "risk_rank",
    "POLICY_DECISION_NAMESPACE",
    "POLICY_MAX_EVIDENCE_REFERENCES",
    "POLICY_MAX_ROLE_LENGTH",
    "POLICY_MAX_RULE_ID_LENGTH",
    "ResponseExecutionStatus",
    "ResponseRequest",
    "ResponseResult",
    "RESPONSE_ID_NAMESPACE",
    "RESPONSE_IDEMPOTENCY_NAMESPACE",
    "RESPONSE_MAX_ERROR_CODE_LENGTH",
    "RESPONSE_MAX_MESSAGE_LENGTH",
    "RESPONSE_MAX_METADATA_DEPTH",
    "RESPONSE_MAX_PROVIDER_LENGTH",
    "RESPONSE_MAX_TARGET_LENGTH",
    "ApprovalStatus",
    "ApprovalRequestCreate",
    "ApprovalDecisionInput",
    "ApprovalRecord",
    "ApprovalPage",
    "APPROVAL_NAMESPACE",
    "APPROVAL_PENDING_TTL",
    "APPROVAL_DECISION_STATUSES",
    "APPROVAL_TERMINAL_STATUSES",
    "APPROVAL_MAX_TARGET_LENGTH",
    "APPROVAL_MAX_COMMENT_LENGTH",
    "APPROVAL_MAX_REASON_LENGTH",
    "APPROVAL_MAX_RULE_ID_LENGTH",
    "APPROVAL_MAX_ROLE_LENGTH",
]